name: TITAN_MISSION
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Execution Target'
        required: true
        default: 'example.com'
jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Exec
        run: |
          echo "EXECUTING TITAN ARROW: amass"
          amass -u ${{ github.event.inputs.target }} || amass ${{ github.event.inputs.target }}
